/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("http://repo.onarandombox.com/content/groups/public/")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.dumptruckman.minecraft:BukkitPlugin:1.3-SNAPSHOT")
    testImplementation("junit:junit:4.8.2")
    testImplementation("org.powermock:powermock-module-junit4:1.4.9")
    testImplementation("org.powermock:powermock-api-easymock:1.4.9")
    testImplementation("org.powermock:powermock-api-mockito:1.4.9")
    testImplementation("org.easymock:easymock:3.0")
    compileOnly("org.bukkit:bukkit:1.13.2-R0.1-SNAPSHOT")
    compileOnly("com.onarandombox.multiverseadventure:Multiverse-Adventure:2.4")
}

group = "com.dumptruckman.minecraft"
version = "3.0.0-SNAPSHOT"
description = "ChestRestock"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
